name: Build nginx-kibana Docker image and push to GitHub Package Registry
on:
  push:
    paths:
      - "nginx-kibana/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish to GitHub Package Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: wuvt/containers/nginx-kibana
        username: wuvt
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        workdir: nginx-kibana
