name: Build etcd-backup Docker image and push to GitHub Package Registry
on:
  push:
    paths:
      - "etcd-backup/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish to GitHub Package Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: wuvt/containers/etcd-backup
        username: wuvt
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        workdir: etcd-backup
