name: Build and push nginx-elasticsearch Docker image
on:
  push:
    tags:
      - 'nginx-elasticsearch-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get release version
      id: get_version
      run: echo RELEASE_VERSION=$(echo ${GITHUB_REF:30}) >> $GITHUB_ENV
    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      with:
        repository: wuvt/nginx-elasticsearch
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: latest,${{ env.RELEASE_VERSION }}
        path: nginx-elasticsearch
        add_git_labels: true
    - name: Build and push Docker image to GitHub Container Registry
      uses: docker/build-push-action@v1
      with:
        repository: wuvt/nginx-elasticsearch
        username: wuvt
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        tags: latest,${{ env.RELEASE_VERSION }}
        path: nginx-elasticsearch
        add_git_labels: true
